<?php

function threebl_analytics_auto_fmr_reports_menu(){
    $items = array();
    $items['threebl_analytics_auto_fmr_reports_cron'] = array(
        'title'=>' Analytics',
        'description'=>'Analytics Views',
        'page callback'=>'threebl_analytics_auto_fmr_reports_cron',
        'access arguments' => array('dashboard analytics'),
    );
    $items['test_fmr_reports_cron'] = array(
        'title'=>' Analytics',
        'description'=>'Analytics Views',
        'page callback'=>'test_fmr_reports',
        'access arguments' => array('dashboard analytics'),
    );
    return $items;
}//end threebl_dashboard_analytics_menu

/**
 * @return bool
 */
function threebl_analytics_auto_fmr_reports_cron()
{
    //Include required class files
    module_load_include('inc', 'threebl_analytics_reports', 'inc/ReportsCronController');
    $objReportsCron = new ReportsCronController();
    $intCnt = $objReportsCron->fnProcessAutoFMRReports();
    
    
	watchdog('Analytics Auto Reports: total emails', "Done==>".$intCnt);
    return true;
}
