<?php

function threebl_eFMR_tracking_menu()
{
    $items = array();
    $items['efmr/tracking'] = array(
        'title'=>'External FMRs Tracking',
        'description'=>'eFMR tracking for only PRConnect affiliates',
        'page callback'=>'threebl_eFMR_tracking_cron',
        'access arguments' => array('administer users')
    );
    return $items;
}//end threebl_analytics_clicks


/**
 * function to collect information for latest published efmr information from
 * database and update the tracking information related PRConnect affiliates
 */
function threebl_eFMR_tracking_cron()
{
    watchdog('eFMR Tracking', 'Checking for eFMRs to track');

    $arrFMRList = array();

    //Include all required files
    module_load_include('inc', 'threebl_affiliate', 'inc/clsTracking');

    //Creating the Object of Class
    $objClsTracking = new clsTracking();

    $sqlLimit ='';

    //GET LATEST FMR
    $sqlSelect  = " SELECT n.nid, n.title, d.field_fmr_date_time_value as date,
    pt.field_prconnect_tracking_value as prflag ";
    $sqlFrom    = " FROM node n
							 JOIN field_data_field_fmr_date_time AS d ON d.entity_id = n.nid
							 JOIN field_data_field_prconnect_tracking as pt ON pt.entity_id = n.nid ";
    $sqlWhere   =  " WHERE n.type = 'efmr' AND n.status = 1 AND
    				pt.field_prconnect_tracking_value = 0 AND
                    (
                        d.field_fmr_date_time_value <= DATE_SUB( NOW() , INTERVAL 4 HOUR)
                        AND
                        d.field_fmr_date_time_value >= DATE_SUB( NOW() , INTERVAL 96 HOUR )
                    )";
    $sqlOrderBy = " ORDER BY prflag, d.field_fmr_date_time_value DESC";


    $sqlQuery 	 = $sqlSelect." ".$sqlFrom." ".$sqlWhere." ".$sqlOrderBy." ".$sqlLimit;
    $arrFMRList  = db_query($sqlQuery)->fetchAll();

    if (count($arrFMRList) > 0) {
        //COLLECT prconnect information
        foreach ($arrFMRList as $efmr) {
            //This is function for prconnect cron
            watchdog('eFMR Tracking', 'Processing nid = '.$efmr->nid);
            $objClsTracking->fnPrconnectCron($efmr->nid);
        }
    }
}
