<?php
function threebl_analytics_clicks_menu()
{
    $items = array();
    $items['ClicksCron'] = array(
        'title'=>' Analytics',
        'description'=>'Analytics Views',
        'page callback'=>'threebl_analytics_clicks_cron2',
        'access arguments' => array('dashboard analytics'),

    );
    return $items;
}//end threebl_analytics_clicks

/**
 * Analytic Click Cron.
 */
function threebl_analytics_clicks_cron2()
{

    //include class file.
    module_load_include('inc', 'threebl_analytics', 'inc/clsClickView');

    //Creating the object for ClickView Class
    $ObjClickView  = new clsClickView();

    $strLimit = "";
    $strLimit = " LIMIT 0, 2000";

    //getting the aid value.
    $intAid = variable_get("aid");
    watchdog('Clicks Cron', 'Beginning AID: '.$intAid);
    
    //if not set to zero
    if (!(int)$intAid) {
        $intAid = 0;
    }

    //getting the value from accesslog table
    $strGetPathDataQ = "SELECT * FROM accesslog WHERE path != 'node/15' AND aid  > $intAid AND path like 'node%' ORDER BY aid ASC ".$strLimit;
    $arrGetPathData = db_query($strGetPathDataQ)->fetchAll();
    //watchdog('Click Cron SQL', $strGetPathDataQ);
    // check if array value exist or not.
    if (is_array($arrGetPathData) && count($arrGetPathData) > 0) {
        @mail('sankets.cuelogic@gmail.com', '3BL Start', "Start of the Code time".date("y-m-d H:i:s"));
        //watchdog('Total Count','<pre>'.Count($arrGetPathData).'</pre>');

        $intCount = 0; //counter for checking record

        //for each start
        foreach ($arrGetPathData as $intKey => $arrGetPathDataDtls) {
            $strPath  	    = $arrGetPathDataDtls->path;
            $strHostName    = $arrGetPathDataDtls->hostname;
            $strReferUrl 	= preg_replace('/[^(\x20-\x7F)]*/', '', $arrGetPathDataDtls->url);
            $strTimeStamp   = $arrGetPathDataDtls->timestamp;
            $strAid 	    = $arrGetPathDataDtls->aid;
            $strDate        = date("Y-m-d H:i:s", $strTimeStamp);

            //getting the media id from above path value.
            $arrSource      = explode("/", $strPath);
            $intMediaId     = (int)$arrSource[1];

            //checking media id exits or not
            if ((int)$intMediaId) {
                //checking media id exist or not for type FMR
                $strGetMediaNodePublishedQ = "SELECT count(*)
                                              FROM  node WHERE nid ='$intMediaId' AND type='fmr' AND status = '1' ";
                $intMediaNodePublished = db_query($strGetMediaNodePublishedQ)->fetchField();

                //if media-id exist or not.

                if ((int)$intMediaNodePublished) {

                    //getting media details
                    $strGetMediaDataQ = "select n.nid, ogm.gid companyOgId
                        from node n
						join og_membership ogm on n.nid = ogm.etid
						where n.nid = '$intMediaId'";

                    $arrGetMediaData = db_query($strGetMediaDataQ)->fetchAll();

                    $intCompanyOgId = 0;
                    $strFMRType = "";

                    //checking media exist or not.

                    if (is_array($arrGetMediaData) && count($arrGetMediaData) > 0) {
                        $intCompanyOgId 	= $arrGetMediaData[0]->companyOgId;

                        //getting FMR Type of particular media-id.
                        $strGetMediaTypeQ = "SELECT field_fmr_type_of_content_value
                                             FROM field_data_field_fmr_type_of_content
                                             WHERE  bundle  = 'fmr' and entity_id  = '$intMediaId'";
                        $strFMRType = db_query($strGetMediaTypeQ)->fetchField();
                    }//end if


                    if ($strFMRType !="" && (int)$intCompanyOgId) {

                        //Checking click count table data already exists or not.
                        $strGet3BlClicksCnt = "SELECT COUNT(nid)
                                               FROM  threebl_analytic_clicks
                                               WHERE nid ='$intMediaId'
                                               AND company_ogid = '$intCompanyOgId'
                                               AND fmr_type = '$strFMRType' AND click_date = '$strDate' ";
                        $intRecordExist = db_query($strGet3BlClicksCnt)->fetchField();

                        //if click table count is zero.

                        if (!(int)$intRecordExist) {
                            //getting Refer-Url
                            $strReferUrl = addslashes(trim(htmlspecialchars($strReferUrl)));

                            $arrAllView = array(); // Array for Click and View table

                            $arrAllView['intCompanyId'] = $intCompanyOgId;
                            $arrAllView['intMediaId'] = $intMediaId;
                            $arrAllView['strChannel'] = '3bl';
                            $arrAllView['strFMRType'] = $strFMRType;
                            $arrAllView['intChannelId'] = 0;
                            $arrAllView['strRefererUrl'] = $strReferUrl;
                            $arrAllView['strClickDate'] = $strDate;
                            $arrAllView['strHostName'] = $strHostName;
                            //echo "<pre>";print_r($arrAllView);echo "</pre>";
                            //Function for insert value in click tables with cron flage is 1
                            $strFlagValue = $ObjClickView->fnAddAllClicks($arrAllView, 1);

                            // Add respective views for the clicked FMR. It will avoid the click/views ratio issue.
                            $arrAllView = array();
                            $arrAllView['intCompanyId'] = $intCompanyOgId;
                            $arrAllView['intMediaId'] = $intMediaId;
                            $arrAllView['strChannel'] = 'click_cron';
                            $arrAllView['strFMRType'] = $strFMRType;

                            $ObjClickView->fnAddAllViews($arrAllView);

                        } else {
                            watchdog('Data Already', $strGet3BlClicksCnt.'Data Already present Aid==' .$intKey);
                        }
                    }
                    ###############################################################
                    #print "<br> $strGetMediaDataQ  => $intJm3BlId => $intCompanyOgId";
                    ### INSERT DATA IN NEW TABLE###################################
                }
            }
        }//end for each

        variable_set("aid", $strAid); //commented by sanket
        watchdog('Clicks Cron', 'Ending AID: '.$strAid);
        //echo $strValue = "\n END Aid = $strAid \n Start Aid => ".$intAid; //commented by sanket
        //@mail('sankets.cuelogic@gmail.com', 'Justmeans - 3BL End',"End of the Code <br/>time".date("y-m-d H:i:s"));
        // echo "<br/><br>Done";die;
    }
}
