<?php
function threebl_client_micro_list_report_menu()
{
    $items = array();
    $items['admin/client-microlist-report-cron'] = array(
        'title'            => 'Client Micro List',
        'description'      => 'Client Micro List Internal Report',
        'page callback'    => 'threebl_client_micro_list_report_cron',
        'access arguments' => array('administer users'),
    );
    return $items;
}

/**
 * Analytic Click Cron.
 */
function threebl_client_micro_list_report_cron()
{
	module_load_include('inc', 'refactor_micro_list', 'inc/MicroListCronController');
	$objMicroListCron = new MicroListCronController();
	$objMicroListCron->fnProcessClientMicroListReportCron();
	
}


