<?php
/*
    Cron function to send weekly Tracking Report in PDF format
*/
function threebl_tracking_auto_affiliates_pdf_reports_menu(){
    $items = array();
    $items['Affiliate/Tracking/PDF'] = array(
        'title'=>' Analytics',
        'description'=>'Analytics Views',
        'page callback'=>'threebl_tracking_auto_affiliates_pdf_reports_cron',
        'access arguments' => array('administer users'),
    );
   
    return $items;
}//end threebl_dashboard_analytics_menu

/**
 * @return bool
 */
function threebl_tracking_auto_affiliates_pdf_reports_cron()
{
	//Include required class files
	module_load_include('inc', 'Refactor_affiliate_tracking', 'inc/AffiliateCronController');
	$objAffiliateCron = new AffiliateCronController();
	$intCnt = $objAffiliateCron->fnProcessTrackingAutoAffiliatesPdfReportsCron(); 

	watchdog('Tracking Auto Reports: total emails', "Done==>".$intCnt);
    return true;
}
