<?php
function threebl_analytics_bemchmark_menu()
{
    $items = array();
    $items['Analytic/Benchmark/Cron'] = array(
        'title'=>'Analytics Benchmark',
        'description'=>'Analytics Benchmark',
        'page callback'=>'threebl_analytics_bemchmark_cron',
        'access arguments' => array('dashboard analytics'),
    );
    return $items;
}

/**
 * Function to calculate average of views and clicks count for Analytics Benchmark
 */
function threebl_analytics_bemchmark_cron()
{
    //Include required class files
    module_load_include('inc', 'threebl_analytics', 'inc/clsAnalytics');
    module_load_include('inc', 'threebl_analytics_reports', 'inc/sendEmail');

    //Object of Analytic class
    $objAnalytics = new clsAnalytics();

    //To get FMR Ids published in last month
    list($arrBenchmarkFMRInfo, $arrFMRIds, $strFMRIds, $arrBenchMarkByMediaType, $arrBenchmarkFMRIds) = $objAnalytics->fnGetLastMonthPublishedFMRIds();

    if ($strFMRIds != "") {
        // GET the Views Related data
        $arrFMRViews = $objAnalytics->fnGetBenchmarkViews($strFMRIds);

        // GET the Click Related data
        $arrFMRClicks = $objAnalytics->fnGetBenchmarkClick($strFMRIds);

        if (count($arrFMRIds) > 0) {

            // $arrBenchmarkFMRInfo Group FMR Ids by Media type and Primary category
            foreach ($arrBenchmarkFMRInfo as $strMediaCategory => $arrGetFMRIds) {

                #Get Media and Primary category group wise FMRs total count
                $intTotalFMRCount = count($arrGetFMRIds);

                // Initialize views and clicks count to 0
                $intTotalViewCount = 0;
                $intTotalClickCount = 0;

                if ((int) $intTotalFMRCount >0) {
                    // Calculate views and clicks count
                    foreach ($arrGetFMRIds as $intFMRId) {
                        // Get total views and clicks count
                        $intTotalViewCount += $arrFMRViews[$intFMRId];
                        $intTotalClickCount += $arrFMRClicks[$intFMRId];
                    }

                    $arrMediaViewsClicks[$strMediaCategory]["views"] = (int)$intTotalViewCount;
                    $arrMediaViewsClicks[$strMediaCategory]["clicks"] = (int)$intTotalClickCount;

                    // Calculate average of views/clicks and stored for each FMR.
                    $objAnalytics->fnCalculateViewsClicksAverage($arrMediaViewsClicks , $intTotalFMRCount, $arrGetFMRIds, "media_category", $strMediaCategory, $arrBenchmarkFMRIds);
                }
            }

            //GET all FMR with Videos
            $arrFMRWithVideos = $objAnalytics->fnGetBenchmarkFMRWithVideo();

            // $arrBenchmarkFMRInfo Group FMR Ids by Media type
            foreach ($arrBenchMarkByMediaType as $strMediaType => $arrGetFMRIdsByMediaType) {

                #Get Media type wise FMRs total count
                $intTotalFMRCountByMediaType = count($arrGetFMRIdsByMediaType);

                // Initialize views and clicks count to 0
                $intTotalViewCountByMediaType = 0;
                $intTotalClickCountByMediaType = 0;

                $intTotalViewCountWithVideo = 0;
                $intTotalClickCountWithVideo = 0;

                $arrFMRViewsInformationWith = array();

                if ((int) $intTotalFMRCountByMediaType > 0) {
                    // Calculate views and clicks count
                    foreach ($arrGetFMRIdsByMediaType as $intFMRIdByMediaType) {
                        // Get total views and clicks count
                        $intTotalViewCountByMediaType += $arrFMRViews[$intFMRIdByMediaType];
                        $intTotalClickCountByMediaType += $arrFMRClicks[$intFMRIdByMediaType];

                        #Check that FMR from with video or not.
                        if (in_array($intFMRIdByMediaType, $arrFMRWithVideos) == true) {
                            $arrFMRViewsInformationWith[] = $arrFMRViews[$intFMRIdByMediaType];

                            $intTotalViewCountWithVideo  += $arrFMRViews[$intFMRIdByMediaType];
                            $intTotalClickCountWithVideo += $arrFMRClicks[$intFMRIdByMediaType];
                        }
                    }

                    $arrMediaViewsClicksByMediaType[$strMediaType]["views"] = $intTotalViewCountByMediaType;
                    $arrMediaViewsClicksByMediaType[$strMediaType]["clicks"] = $intTotalClickCountByMediaType;

                    //Assign with video count to total count of media.
                    $intTotalFMRCountWithVideo = count($arrFMRViewsInformationWith);
                    $arrMediaViewsClicksByMediaType[$strMediaType]["withvideo"]['fmrcount'] = count($arrFMRViewsInformationWith);
                    $arrMediaViewsClicksByMediaType[$strMediaType]["withvideo"]['views'] = (int) $intTotalViewCountWithVideo;
                    $arrMediaViewsClicksByMediaType[$strMediaType]["withvideo"]['clicks'] = (int) $intTotalClickCountWithVideo;

                    //Assign with out video count to 0
                    #Views
                    $arrMediaViewsClicksByMediaType[$strMediaType]["withoutvideo"]['views'] = (int) $intTotalViewCountByMediaType - $intTotalViewCountWithVideo;
                    #Clicks
                    $arrMediaViewsClicksByMediaType[$strMediaType]["withoutvideo"]['clicks'] = (int) $intTotalClickCountByMediaType - $intTotalClickCountWithVideo;
                    #FMR Count
                    $arrMediaViewsClicksByMediaType[$strMediaType]["withoutvideo"]['fmrcount'] = (int) $intTotalFMRCountByMediaType - $intTotalFMRCountWithVideo;

                    // Calculate average of views/clicks and stored for each FMR.
                    $objAnalytics->fnCalculateViewsClicksAverage($arrMediaViewsClicksByMediaType, $intTotalFMRCountByMediaType, $arrGetFMRIdsByMediaType, "media", $strMediaType);
                }
            }
        }
    }

    //Set Subject for report cron email
    $strSubject = "Benchmark Alert";

    //Set the message for the email
    $strMessage = "This report is sent automatically for Benchmarks Alert.<br/><br/>Thank you,<br/>The 3BL Media Team<br/>";

    //$strRecipientMail = "dfulton@3blmedia.com,consult@3blmedia.com";
    $strRecipientMail = "dfulton@3blmedia.com,tushar.mate@cuelogic.co.in";
    // Send Monthly report
    fnSendEmail("3BL Media", "no-reply@3blmedia.com", $strRecipientMail, $strSubject, $strMessage);
    exit;
}
